### ISSUE TITLE
 <div><input type="checkbox" name="" id="" id="myCheck">I accept all the Terms & Conditions</div>

### ISSUE THREAD

**Issue by aimanzi** [Fullstack-Alfanar/team-work4#11]
hi team 4 :
in the signup page line 22 
the input has two id
for you attintention , please fix it

**Comment by nevensh** [comment]
hey aiman . 
the Id was impty but I remove it , it's ok ?
check it .

**Comment by aimanzi** [comment]
yes i knew that it empty  dear , but for the arrangment only
