### ISSUE TITLE
id button

### ISSUE THREAD

**Issue by MurjanAssadi** [Fullstack-Alfanar/team-work4#13]
https://github.com/Fullstack-Alfanar/team-work4/blob/1c344c952e779033507adfddde236773f25010c2/html%20pages/home.page.html#L27

you forget to add an id to the button

**Comment by nevensh** [comment]
hey murjan 
I haven't used the id yet , for what i put id now ?

**Comment by tyseerhen** [comment]
ok please make sure to use ides when you make a javascript files
