### ISSUE TITLE
to do list

### ISSUE THREAD

**Issue by nevensh** [Fullstack-Alfanar/team-work4#4]
**To Do list** 
- [x] 1.     create index.html 
- [x] 2.     create html files 
- [x] **home page html:contain:**
- [ ]  animations 
- [ ]  sign in button 
- [ ]  sign up button

- [x] **signup page html:**
   
- [ ] check if the user member on the site
- [ ] validate user
- [ ] validate age
- [ ] validate Email
- [ ] validate password 
- [ ] validate confirm password
- [ ] set cookies

- [x] **sign In page html :**

- [ ] check sign in user
- [ ] check Database user
- [ ] get from local
- [ ] set cookies
- [ ] the button switch us to swimming club site .

- [x] **forget password  page html :**
- [ ] check  exiting of Email in database
- [ ] reroute to re new password page

- [ ] **swimming club site page html :**
- [ ] show existing courses

- [x] 3.    create CSS files
- [x] home page CSS
- [ ] signup page CSS
- [ ] sign in page CSS
- [ ] forget password CSS
- [ ]  index CSS
- [ ] swimming club page site CSS
- [ ] Renew password page  

- [ ] 4.  create script file
- [ ] 5.     create images file
- [ ] 6.    create README.md

**Comment by aimanzi** [comment]
Nice
